var data={
    "info":{
        "name":"李丹",
        "job":"前端工程师",
        "edu":"湖南科技大学",
        "gra":"2019-6",
        "mail":"l_d_lidan@163.com",
        "tel":"187732XXXXX",
        "github":"https://github/charisld.com"
    },
    "skills":{
        "skill1":"CSS",
        "skill2":"HTML",
        "skill3":"JavaScript",
        "skill4":"jQuery",
        "skill5":"React",
        "skill6":"Bootstrap"
    },
    "projects":{
            "proname":[
                "项目一",
                "项目二",
                "项目三"
            ],
            "des":[
                "项目一的介绍",
                "项目二的介绍",
                "项目三的介绍"
            ],
            "pro1item":[
                "HTML",
                "CSS",
                "JS",
                "JQUERY",
                "BOOTSTRAP",
                    "PHP"
            ],
            "pro1intro":[
                "知识点一的描述语句",
                "知识点一的描述语句",
                "知识点一的描述语句",
                "知识点一的描述语句",
                "知识点一的描述语句",
                "知识点一的描述语句"
            ],
            "pro2item": [
                "HTML",
                "CSS",
                "JS",
                "JQUERY",
                "BOOTSTRAP",
                "PHP"
            ],
            "pro2intro":[
                "知识点二的描述语句",
                "知识点二的描述语句",
                "知识点二的描述语句",
                "知识点二的描述语句",
                "知识点二的描述语句",
                "知识点二的描述语句"
            ],
            "pro3item":[
                "HTML",
                "CSS",
                "JS",
                "JQUERY",
                "BOOTSTRAP",
                "PHP"
            ],
            "pro3intro":[
                "知识点三的描述语句",
                "知识点三的描述语句",
                "知识点三的描述语句",
                "知识点三的描述语句",
                "知识点三的描述语句",
                "知识点三的描述语句"
            ],
            "address":[
                "http://1",
                "http://2",
                "http://3"
            ]    
        },
        "contact":[
            "10652XXXXX",
            "weixinhao",
            "http://github.com",
            "137859XXXX",
            "2848993@qq.com"
        ]
}